### ISSUE TITLE
Feature: Expanding example

### ISSUE THREAD

**Issue by syedkhairi** [walker-tx/svelte5-tanstack-table-examples#2]
Hello, brilliant set of examples - was wondering if it's possible to compose one involving `expand` rows as I've tried myself, and not quite working. Thanks in advance!

**Comment by walker-tx** [comment]
> Hello, brilliant set of examples

Why thank you!

> was wondering if it's possible to compose one involving expand rows as I've tried myself, and not quite working. Thanks in advance!

Sure! To clarify - you're looking for something [like this](https://tanstack.com/table/latest/docs/framework/react/examples/expanding)?

Do you have a repro that would help me understand the specific issues your facing? This may also be an issue with my own implementation of the adapter.

**Comment by syedkhairi** [comment]
I'll whip up a repro so can help others, but I managed to do so for my user case - I've missed out the states etc.

Completely new to TanStack - so pardon me!

```
let expanded = $state<ExpandedState>({});

// Create the table.
const table = createSvelteTable({
    get data() {
        return dataState;
    },
    columns: columnDefs,
    getRowCanExpand: (row) => true,
    getCoreRowModel: getCoreRowModel(),
    getExpandedRowModel: getExpandedRowModel(),
    state: {
        get expanded() {
            return expanded;
        },
    },
    onExpandedChange: (updater) => {
        if (typeof updater === "function") {
            expanded = updater(expanded);
        } else {
            expanded = updater;
        }
    },
});
```

```
{#snippet item(row: Row<Folder>)}
    {#if row.getCanExpand()}
        {@const folder = row.original}
        {@const isOpen = row.getIsExpanded()}
        <button
            type="button"
            onclick={row.getToggleExpandedHandler()}
        >
            {folder.name}
        </button>

        {#if isOpen}
            <!-- expanded content here -->
        {/if}
    {/if}
{/snippet}
```

**Comment by walker-tx** [comment]
@syedkhairi Thank you!

I added the example to the repo: https://svelte5-and-tanstack-table-v8.vercel.app/examples/row-expansion
