### ISSUE TITLE
getRowId

### ISSUE THREAD

**Issue by Tihomir971** [walker-tx/svelte5-tanstack-table-examples#3]
Hi, I tried to add: getRowId: row => row.id but i get type error. Any suggestion how can i change selected row id from default?

**Comment by walker-tx** [comment]
Would you share some code, and/or a minimal reproduction please?

**Comment by Tihomir971** [comment]
> Would you share some code, and/or a minimal reproduction please?

I apologize. I thought huntabyte (shadcn-svelte) used your code. With your functions it works as it should :)
